#! /bin/sh
set -e

OUT="$1"
LIST="$2"

trap "rm -f $OUT.tmp" 0

cat > $OUT.tmp <<EOF
/* Autogenerated list of builtin modules. */
#include <linux/module.h>

const char *builtin_modnames[] = {
EOF

sed -e 's@.*/\(.*\)\.ko@\t"\1"@' -e 's@[,-]@_@g' -e 's@$@,@' < $LIST >> $OUT.tmp
cat >> $OUT.tmp <<EOF
	NULL
};
EOF

mv $OUT.tmp $OUT
